# see https://s.apache.org/asfyaml
github:
  description: "Apache Maven Doxia site"
  homepage: https://maven.apache.org/doxia/
  labels:
    - java
    - build-management
    - apache-maven
    - maven
    - doxia
